# .github/workflows/reusable.yml
name: Reusable Workfloww

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      my_input:
        description: 'A custom input string'
        required: false
        type: string
        default: "hello"
      run-on:
        description: 'A custom input string'
        required: false
        type: string
        default: ubuntu-latest

jobs:
  display_input:
    runs-on: ${{ inputs.run-on }}
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: VotreMotDePasse!  # Remplacez par un mot de passe fort
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    steps:
      - name: Show the input
        run: echo ${{ inputs.my_input }}
      - uses: actions/checkout@v4
      - name: Attendre le démarrage de SQL Server
        run: |
          sleep 30s # Temps nécessaire au démarrage du conteneur
      - name: Vérifier la connexion à SQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools
          export PATH="$PATH:/opt/mssql-tools/bin"
          sqlcmd -S localhost -U sa -P "VotreMotDePasse!" -Q "SELECT @@VERSION"
