# .github/workflows/reusable.yml
name: Reusable Workfloww

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      my_input:
        description: 'A custom input string'
        required: false
        type: string
        default: "hello"
      run-on:
        description: 'A custom input string'
        required: false
        type: string
        default: ubuntu-latest

jobs:
  display_input:
    runs-on: ${{ inputs.run-on }} 
    steps:
      - name: Show the input
        run: echo ${{ inputs.my_input }} 
