# .github/workflows/reusable.yml
name: Reusable Workfloww

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      my_input:
        description: 'A custom input string'
        required: false
        type: string
        default: "hello"
      run-on:
        description: 'A custom input strinhg'
        required: false
        type: string
        default: ubuntu-latest

jobs:
  test:
    runs-on: ${{ inputs.run-on }}
    steps:
      - name: Show the input
        run: echo ${{ inputs.my_input }}
  display_input:

    runs-on: ${{ inputs.run-on }}
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: VotreMotDePasse!  # Remplacez par un mot de passe fort
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    steps:
      - name: Show the input
        run: echo ${{ inputs.my_input }}
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
         fetch-tags: 0
      - name: get tags
        id: set_vars
        run: |
            LAST_TAG=/usr/bin/git describe --tags --abbrev=0
            EXIT_CODE=$?
            if [ $EXIT_CODE -eq 0 ]; then
            # Si la commande réussit, utilisez le tag trouvé
              NAME=$LAST_TAG
            else
                # Si aucun tag n'est trouvé (code 128), utilisez une valeur par défaut
              NAME="v0.0.0-initial"
            fi
            echo "package_name=$NAME" >> $GITHUB_OUTPUT
      - name: latest tag
        run: |
           PACKAGE_NAME="${{ steps.set_vars.outputs.package_name }}"
           echo $PACKAGE_NAME
      - name: Attendre le démarrage de SQL Server
        run: |
          sleep 5s # Temps nécessaire au démarrage du conteneur
      - name: Vérifier la connexion à SQL Server
        run: |
          sudo apt-get update && sudo apt-get install -y lsb-release
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
      - name: Update apt and install mssql-tools
        run: |
          sudo apt-get update -y
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
      - name: Ajouter les outils au PATH
        run: |
          export PATH="$PATH:/opt/mssql-tools18/bin"
          sqlcmd -S localhost -U sa -P "VotreMotDePasse!" -Q "SELECT @@VERSION" -C
